spring.application.name=delivery-api
# Configura\u00E7\u00E3o do servidor
server.port=8080

# Configura\u00E7\u00E3o do H2 Database

spring.datasource.url=jdbc:h2:mem:deliverydb;DATABASE_TO_UPPER=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=123456

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#
# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configura\u00E7\u00F5es de desenvolvimento
spring.devtools.restart.enabled=true

# Configura\u00E7\u00F5es espec\u00EDficas para JDK 21
spring.jpa.open-in-view=false
logging.level.org.springframework.web=DEBUG

# Executar scripts SQL automaticamente
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Swagger Configuration
springdoc.api-docs.path=/api-docs 
springdoc.swagger-ui.path=/swagger-ui.html 
springdoc.swagger-ui.operationsSorter=method 
springdoc.swagger-ui.tagsSorter=alpha 